---
- name: Setup SSH access for ansible user
  hosts: all
  become: true
  vars:
    ssh_user: ansible
    ssh_pubkey_path: /home/ansible/.ssh/id_rsa.pub
    ssh_dir: "/home/{{ ssh_user }}/.ssh"
    ssh_auth_file: "{{ ssh_dir }}/authorized_keys"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0700'

    - name: Copy public key to authorized_keys
      copy:
        src: "{{ ssh_pubkey_path }}"
        dest: "{{ ssh_auth_file }}"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0600'
