---
- name: Setup SSH access for ansible user
  hosts: all
  become: true
  vars:
    ssh_user: vagrant
    target_user: ansible
    ssh_pubkey_path: /home/ansible/.ssh/id_rsa.pub
    ssh_dir: "/home/{{ target_user }}/.ssh"
    ssh_auth_file: "{{ target_user }}/authorized_keys"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: "{{ target_user }}"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0700'

    - name: Copy public key to authorized_keys
      copy:
        src: "{{ ssh_pubkey_path }}"
        dest: "{{ ssh_auth_file }}"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'