Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"

  machines = {
    "etcd01" => { ip: "192.168.56.10", ports: [] },
    "pgsql01" => { ip: "192.168.56.11", ports: [5432] },
    "pgsql02" => { ip: "192.168.56.12", ports: [5432] },
    "docker01" => { ip: "192.168.56.13", ports: [9090, 3000] }
  }

  machines.each do |name, opts|
    config.vm.define name do |vm|
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: opts[:ip]
      opts[:ports].each do |port|
        vm.vm.network "forwarded_port", guest: port, host: port
      end
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
      
      # Создание пользователя ansible
      vm.vm.provision "shell", inline: <<-SHELL
        sudo useradd -m -s /bin/bash ansible
        sudo mkdir -p /home/ansible/.ssh
        sudo chmod 700 /home/ansible/.ssh
        sudo chown -R ansible:ansible /home/ansible/.ssh

        # Добавление публичного ключа (замени на свой)
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOlnoNjJYpvl4K28xlM+eEkRvdKVNBM5hS89QuWBObV0Oc7MgLSKB1h1HNJXF419H54uBZlFs3XfQfP05mot+61ygeR2IJJjBj+NPaErA3+7q7n2FbfZDxy4L//5ICB2Vqu/JsYO9Jq7wpjK91ToXX4QcKTb0mQf5ww+/Xy+Fb6YCjrtlCJFUNLDx0FeXGPC3LXbDXs1P1NQ7MJ7PoI+AYf1o0KZjjTy72Lo28y1WJpOybq5FH9PKzG9eL6eXQMCB68E5hhV9GPCL6rifVCntp4JrUn9T27ABsALwsWjKtrhyNMO1dvpO1BYykWlz8/x5pO8SiuQGqQLV+lLycIIyT noname" | sudo tee /home/ansible/.ssh/authorized_keys
        sudo chmod 600 /home/ansible/.ssh/authorized_keys
        sudo chown ansible:ansible /home/ansible/.ssh/authorized_keys
      SHELL

       # Установка Ansible только на docker01
      if name == "docker01"
        vm.vm.provision "shell", inline: <<-SHELL
          sudo dnf install -y epel-release
          sudo dnf install -y ansible
        SHELL
      end
      
    end
  end
end
