Vagrant.configure("2") do |config|
  config.vm.box = "oraclelinux/8"

  machines = {
    "etcd01" => { ip: "192.168.56.10", ports: [] },
    "pgsql01" => { ip: "192.168.56.11", ports: [5432] },
    "pgsql02" => { ip: "192.168.56.12", ports: [5432] },
    "docker01" => { ip: "192.168.56.13", ports: [9090, 3000] }
  }

  machines.each do |name, opts|
    config.vm.define name do |vm|
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: opts[:ip]
      opts[:ports].each do |port|
        vm.vm.network "forwarded_port", guest: port, host: port
      end
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end

       # Установка Ansible только на docker01
      if name == "docker01"
        vm.vm.provision "shell", inline: <<-SHELL
          sudo dnf install -y epel-release
          sudo dnf install -y ansible
        SHELL
      end

    end
  end
end
