Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/oracle-linux-8"
  config.vm.box_version = "8.10.5"

  machines = {
    "etcd01" => {
      ip: "192.168.56.10",
      ports: [],
      memory: 512,
      cpus: 1
    },
    "pgsql01" => {
      ip: "192.168.56.11",
      ports: [{ guest: 5432, host: 5532 }],
      memory: 1024,
      cpus: 1
    },
    "pgsql02" => {
      ip: "192.168.56.12",
      ports: [{ guest: 5432, host: 5533 }],
      memory: 1024,
      cpus: 1
    },
    "docker01" => {
      ip: "192.168.56.13",
      ports: [{ guest: 9090, host: 19090 }, { guest: 3000, host: 13000 }],
      memory: 2048,
      cpus: 1
    }
  }

  machines.each do |name, opts|
    config.vm.define name do |vm|
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: opts[:ip]

      opts[:ports].each do |port|
        vm.vm.network "forwarded_port", guest: port[:guest], host: port[:host]
      end if opts[:ports]

      vm.vm.provider "virtualbox" do |vb|
        vb.memory = opts[:memory]
        vb.cpus = opts[:cpus]
      end
      
      # Создание пользователя ansible
      vm.vm.provision "shell", inline: <<-SHELL
        sudo useradd -m -s /bin/bash ansible
        sudo mkdir -p /home/ansible/.ssh
        sudo chmod 700 /home/ansible/.ssh
        sudo chown -R ansible:ansible /home/ansible/.ssh
      SHELL

       # Установка Ansible только на docker01
      if name == "docker01"
        vm.vm.provision "shell", inline: <<-SHELL
          sudo dnf install -y epel-release
          sudo dnf install -y ansible
        SHELL
      end
    end
  end
end
