---
- name: ensure dnf cache is up to date
  ansible.builtin.dnf: 
    update_cache: true

- name: Reset postgres module list
  ansible.builtin.shell: yes | dnf module reset postgresql

- name: Enable PostgreSQL {{postgresql_version}} module
  ansible.builtin.shell: yes | dnf module enable postgresql:{{postgresql_version}}

- name: Install Postgresql
  ansible.builtin.dnf:
    name: 
      - postgresql-server
      - python3-pip
    state: latest

- name: Install Postgresql
  ansible.builtin.dnf:
    name: 
      - python3-psycopg2
      - pgaudit
    state: latest

- name: Install Patroni via pip
  pip:
    name: patroni[etcd]
    executable: pip3

- name: Create Patroni config
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
    mode: 0644

- name: Create systemd unit for Patroni
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    mode: 0644
  ansible.biltin.meta: reboot

- name: Enable and start Patroni
  systemd:
    name: patroni
    enabled: yes
    state: started


- name: Create PostgreSQL User
  community.postgresql.postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ pg_user_pass }}"
    role_attr_flags: "REPLICATION" 


- name: Перезапустить сервис снова
  ansible.builtin.meta: flush_handlers