---
# tasks file for docker
- name: Enable Docker CE repo
  dnf:
    name: https://download.docker.com/linux/centos/docker-ce.repo
    state: present

- name: Install Docker
  dnf:
    name: docker-ce
    state: latest

- name: Docker config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
  - start