- hosts: etcd
  become: yes
  roles:
    - etcd

- hosts: docker
  become: yes
  roles:
    - docker

- hosts: pg_cluster
  become: yes
  roles:
    - postgresql_patroni
    - postges_exporter

- hosts: all
  become:
  roles:
    - node_exporter