- hosts: all
  become: yes
  roles:
    - add_ssh

# - hosts: etcd
#   become: yes
#   roles:
#     - etcd

# - hosts: docker
#   become: yes
#   roles:
#     - docker

# - hosts: pg_cluster
#   become: yes
#   roles:
#     - postgresql_patroni